version: "3.3"

services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: app/
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
